stages:
  - docs
  - prebuild
  - build
  - release

include:
  - project: fabnum-minarm/igloo/gitlab-templates
    file:
      - /pandoc.all.yml
      - /mdbook.auto.yml
      - /pages.auto.yml
      - /releaser.auto.yml
      - /npm.yml

variables:
  GENERIC_PACKAGE_NAME: stargate

pack-pm2:
  extends: .igloo:npm:install
  cache:
    policy: pull
  stage: prebuild
  before_script: []
  script:
    - npm i -g pm2
    - mkdir -p pm2 && cd $_
    - tar -C $(npm list -g --depth=0 | head -1)/node_modules -cjf $CI_PROJECT_DIR/pm2.tar.bz2 pm2
    - ls -al
  artifacts:
    paths:
      - pm2.tar.bz2

.igloo:build:docs:pandoc:
  rules:
    - if: "$CI_COMMIT_BRANCH || $CI_COMMIT_TAG"
      exists:
        - metadata.pandoc.yml
        - src/??-*.md
      when: always
    - when: never

pages:
  only:
    - master
